ruby "2.5.1"

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "thin"
gem "sinatra"
gem "rinruby", :github => "virtualstaticvoid/rinruby", :branch => "master"
