#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

# install ruby
apt-get update -q
apt-get install -qy --no-install-recommends ruby
apt-get clean
rm -rf /var/lib/apt/lists/*

gem install bundler --no-document

export BUNDLE_SILENCE_ROOT_WARNING=1 # disable warning about running bundler as root
bundle install
