#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

# install java jdk
apt-get update -q
apt-get install -qy --no-install-recommends openjdk-8-jdk
apt-get clean
rm -rf /var/lib/apt/lists/*

# configure R for Java
R CMD javareconf &> /dev/null

# naive compile of Java program (working directory is /app)
javac *.java
