#!/bin/bash

set -e

export DEBIAN_FRONTEND=noninteractive

# install python and pip
apt-get update -q
apt-get install -qy --no-install-recommends python3 python3-dev python3-pip
apt-get clean
rm -rf /var/lib/apt/lists/*

# install dependencies (in requirements.txt)
pip install -r requirements.txt
